apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
          matchLabels:
                  name: my-postgres-app-pod
                  group: example
  template:
          metadata:
                name: my-postgres-app-pod
                labels:
                        name: my-postgres-app-pod
                        group: example
          spec:
                containers:
                        - name: db
                          image: postgres
                          ports:
                            - containerPort: 5432
                          env:
                            - name: POSTGRES_HOST_AUTH_METHOD
                              value: trust
