apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
        name: db-service
        group: example
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
      name: my-postgres-app-pod
      group: example
