apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
        name: my-redis-app-pod
        group: example
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
        name: my-redis-app-pod
        group: example
