apiVersion: v1
kind: Pod
metadata:
  name: my-redis-app-pod
  labels:
    name: my-redis-app-pod
    group: example
spec:
  containers:
    - name: redis
      image: redis
      ports:
              - containerPort: 6379
