apiVersion: v1
kind: Pod
metadata:
  name: my-result-app-pod
  labels:
    name: my-result-app-pod
    group: example
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
              - containerPort: 80
