apiVersion: v1
kind: Pod
metadata:
  name: my-voting-app-pod
  labels:
    name: my-voting-app-pod
    group: example
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
              - containerPort: 80
