apiVersion: v1
kind: Pod
metadata:
  name: my-worker-app-pod
  labels:
    name: my-worker-app-pod
    group: example
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker
